version: '3'

services:
  web:
    container_name: django-docker
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:mysql

  db:
    container_name: django-docker-db
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment: 
      MYSQL_DATABASE: django_docker
      MYSQL_USER: ****
      MYSQL_PASSWORD: ****
      MYSQL_ROOT_PASSWORD: ****
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
    ports: 
      - 3306:3306